### ISSUE TITLE
Possible to extend default dictionaries included when using `cspell` only with pre-commit?

### ISSUE THREAD

**Issue by turo-mwong** [streetsidesoftware/cspell-cli#590]
Couple things:

1. [documentation] First it's not 100% clear which default dictionaries are available when using `cspell` only with pre-commit. I've found this page https://cspell.org/docs/dictionaries/#dictionaries which seems like the list of defaults? Also it was a little confusing when running `trace` I assumed any of the dictionaries from results should be included with default. This project's main  README.md should maybe reference the default dictionaries which are included when using pre-commit only.

2. [feature request x2] 
   - If this is the default list ^ then is it either already possible or possible in the future to extend the list? i.e. through the `cspell` configuration or pre-commit config. 
   - Would it be possible to add a new option to `trace` to only search the default dictionaries for the given word? (therefore giving the tool to setup pre-commit configurations with less friction)

```command
# Input
$ cspell trace --default-dictionaries referer

# Output
referer - default1    node_modules/@cspell/dict-1/dict/default1.txt
referer - default2    node_modules/@cspell/dict-2/dict/default2.txt
```

Scenario example, 

I want the make an exception for the word `"referer"`. My intuition tells me there must be a `cspell` dictionary for this. I run `trace` and see the dictionaries are apart of this. I need to cross reference dictionaries from the result and in [the default dictionaries list](https://cspell.org/docs/dictionaries/#dictionaries) to determine what dictionary I can use.

1. None of the dictionaries that include my word `"referer"` match the project tech-stack (I don't want to include the `typescript` dictionary for a Java project)
2. The list doesn't include the dictionary I want which would be more suitable .. i'm guessing like an "http" dictionary or specifically based on my `trace` results `@cspell/dict-software-terms/dict/webServices.txt`

**Comment by Jason3S** [comment]
@turo-mwong,

A few things:
1. `cspell` and `cspell-cli` are the same. `cspell-cli` repackages `cspell` just so it can be included by `pre-commit`.
1. `referer` is a misspelling that made it into the HTML spec.
2. `softwareTerms` does not have `referer`. The trailing `*` indicates that it is enabled.
3. Should the HTML dictionary have `referer`? probably since it is part of the spec.

All dictionaries included with `cspell` are included with `cspell-cli`. The trace command lists  all the currently enabled dictionaries and any that include the word.

<img width="731" alt="image" src="https://github.com/user-attachments/assets/d7fb1d62-a97e-4727-9378-a8cb1a094c94">

To see a list of all dictionaries try:
```
cspell-cli trace --language-id java "referer" --all 
```

**Comment by turo-mwong** [comment]
Closing due to misunderstanding of the tool.
