### ISSUE TITLE
glob pattern missing dot prefix

### ISSUE THREAD

**Issue by AnthonyElcocks** [streetsidesoftware/cspell-cli#77]
I used the example pattern cspell `"**/{*,.*}/**/*.*"` given in the strict mode section found here https://cspell.org/docs/globs/ ... and ran against a vscode project (in windows 10) which has dot files in root
e.g. .eslintrc.js and .gitignore
This pattern matches the .vscode folder in root but not the files. It matches files in the top level folders (src/index.js) but does not match dot files and folders recursively, so misses src/.foo and src/component/.hello
1/4 .\.vscode\launch.json 385.10ms
2/4 .\src\index.js 26.73ms
3/4 .\src\components\hello.js 8.07ms
4/4 .\test\index-test.js 7.13ms

I can change the pattern to `{*,.*,**,*.*}` and match the top level files, but lose the .vscode folder
1/8 .\.eslintrc.js 408.16ms
2/8 .\.gitignore 4.51ms
3/8 .\cspell.json 5.15ms
4/8 .\package.json 5.33ms
5/8 .\src\index.js 4.85ms
6/8 .\src\components\hello.js 4.46ms
7/8 .\test\index-test.js 7.07ms
8/8 .\webpack.config.js 2.15ms

I have been manipulating this pattern for several hours now and cannot get it to match all files and directories recursively, starting at the root.

Any help would be appreciated. Either I found a bug or my limited knowledge of regex is failing me

**Comment by Jason3S** [comment]
@AnthonyElcocks,

Globs can be very frustrating since the documentation out there is very poor and the behavior changes from implementation to implementation. Note: they are NOT regex patterns, so regex rules will not work.

See if this works for you:
`"**/{*,.*,.*/**/{*,.*,.*/**}}"`

The above will do two levels of hidden directories / files.

Please note, you can give it more than one glob, no need to try and squeeze all the logic into a single glob.

In the current implementation, it is not possible (without a code change), to recursively search hidden directories. You can open a feature request for a command line option to make that possible. Please do that here: [Issues · streetsidesoftware/cspell](https://github.com/streetsidesoftware/cspell/issues)

**Comment by Jason3S** [comment]
@AnthonyElcocks 
I have updated the `cspell` dependency to allow for the `--dot` argument.
